# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"%\n\rBinaryRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\x42\n\nAddService\x12\x34\n\x03\x41\x64\x64\x12\x19.calculator.BinaryRequest\x1a\x12.calculator.Result2L\n\x0fSubtractService\x12\x39\n\x08Subtract\x12\x19.calculator.BinaryRequest\x1a\x12.calculator.Result2L\n\x0fMultiplyService\x12\x39\n\x08Multiply\x12\x19.calculator.BinaryRequest\x1a\x12.calculator.Result2H\n\rDivideService\x12\x37\n\x06\x44ivide\x12\x19.calculator.BinaryRequest\x1a\x12.calculator.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BINARYREQUEST']._serialized_start=32
  _globals['_BINARYREQUEST']._serialized_end=69
  _globals['_RESULT']._serialized_start=71
  _globals['_RESULT']._serialized_end=95
  _globals['_ADDSERVICE']._serialized_start=97
  _globals['_ADDSERVICE']._serialized_end=163
  _globals['_SUBTRACTSERVICE']._serialized_start=165
  _globals['_SUBTRACTSERVICE']._serialized_end=241
  _globals['_MULTIPLYSERVICE']._serialized_start=243
  _globals['_MULTIPLYSERVICE']._serialized_end=319
  _globals['_DIVIDESERVICE']._serialized_start=321
  _globals['_DIVIDESERVICE']._serialized_end=393
# @@protoc_insertion_point(module_scope)
